<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-13T12:17:08 ICT" name="Default suite" finished-at="2022-04-13T12:17:33 ICT" duration-ms="24357">
    <groups>
    </groups>
    <test started-at="2022-04-13T12:17:08 ICT" name="Default test" finished-at="2022-04-13T12:17:33 ICT" duration-ms="24357">
      <class name="com.poly.AutomationTest.DeleteTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4]" started-at="2022-04-13T12:17:08 ICT" name="init" finished-at="2022-04-13T12:17:08 ICT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4]" started-at="2022-04-13T12:17:11 ICT" name="setUp" finished-at="2022-04-13T12:17:23 ICT" duration-ms="11867" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="multiplePhim(java.lang.String)[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4]" started-at="2022-04-13T12:17:23 ICT" name="multiplePhim" data-provider="DeletephimData" finished-at="2022-04-13T12:17:30 ICT" duration-ms="7134" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8080/PS14885_ASM_JAVA4/manager/editPage/index]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/PS14885_ASM_JAVA4/manager/editPage;jsessionid=0426CF95920FFB9A76233350816838F4/deletePH] but found [http://localhost:8080/PS14885_ASM_JAVA4/manager/editPage/index]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/PS14885_ASM_JAVA4/manager/editPage;jsessionid=0426CF95920FFB9A76233350816838F4/deletePH] but found [http://localhost:8080/PS14885_ASM_JAVA4/manager/editPage/index]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.poly.AutomationTest.DeleteTest.multiplePhim(DeleteTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiplePhim -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4]" started-at="2022-04-13T12:17:31 ICT" name="tearDown" finished-at="2022-04-13T12:17:31 ICT" duration-ms="771" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiplePhim status=FAILURE method=DeleteTest.multiplePhim(java.lang.String)[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="destroy()[pri:0, instance:com.poly.AutomationTest.DeleteTest@563f38c4]" started-at="2022-04-13T12:17:31 ICT" name="destroy" finished-at="2022-04-13T12:17:33 ICT" duration-ms="1279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- com.poly.AutomationTest.DeleteTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
